In [128]:
import pandas as pd
import numpy as np
import re

In [133]:
  diffusion= {
    "fraction_2025": '0.1',
    "fraction_2030": 0.3,
    "fraction_2035": 0.8
  }

for k in diffusion.keys(): 
    print(k)
    diffusion[re.sub('fraction_', '', k)] = diffusion.pop(k)
#     k = re.sub('fraction_', '', k)

print(diffusion)

fraction_2025
fraction_2030
fraction_2035
{'2025': '0.1', '2030': 0.3, '2035': 0.8}

In [123]:
  diffusion= {
    "2025": '0.1',
    "2030": 0.3,
    "2035": 0.8
  }
    
if '2020' not in diffusion.keys():
    print('uuuu')
    diffusion['2020'] = None
if '2040' not in diffusion.keys():
    print('uuuu')
    diffusion['2040'] = None
    
        
df = pd.DataFrame(diffusion.items(), columns=['years','diff'])
df['years'] = pd.to_datetime(df['years'])
df.index = df['years']
df.drop(['years'], axis=1, inplace=True)
df["diff"] = pd.to_numeric(df["diff"], downcast="float")
df = df.resample('Y').mean()
df

uuuu
uuuu

            diff
years
2020-12-31   NaN
2021-12-31   NaN
2022-12-31   NaN
2023-12-31   NaN
2024-12-31   NaN
2025-12-31   0.1
2026-12-31   NaN
2027-12-31   NaN
2028-12-31   NaN
2029-12-31   NaN
2030-12-31   0.3
2031-12-31   NaN
2032-12-31   NaN
2033-12-31   NaN
2034-12-31   NaN
2035-12-31   0.8
2036-12-31   NaN
2037-12-31   NaN
2038-12-31   NaN
2039-12-31   NaN
2040-12-31   NaN

In [96]:
df2 = df.interpolate(method='linear', limit_direction='both', limit_area='inside')
df2

            diff
years
2020-12-31   NaN
2021-12-31   NaN
2022-12-31   NaN
2023-12-31   NaN
2024-12-31   NaN
2025-12-31  0.10
2026-12-31  0.14
2027-12-31  0.18
2028-12-31  0.22
2029-12-31  0.26
2030-12-31  0.30
2031-12-31  0.40
2032-12-31  0.50
2033-12-31  0.60
2034-12-31  0.70
2035-12-31  0.80
2036-12-31   NaN
2037-12-31   NaN
2038-12-31   NaN
2039-12-31   NaN
2040-12-31   NaN

In [102]:
# print(type(df2['diff'][3]))


if df2['diff'].isnull().values.any():
    print('WARNING: Not enough data were provided for first and last years ' 
          'of the considered simulation period.\n'
          'The simulation will continue assuming plausible diffusion fraction values.')
    df3 = df2.interpolate(method='linear').bfill()
df3

WARNING: Not enough data were provided for first and last years of the considered simulation period.
The simulation will continue assuming plausible diffusion fraction values.

            diff
years
2020-12-31  0.10
2021-12-31  0.10
2022-12-31  0.10
2023-12-31  0.10
2024-12-31  0.10
2025-12-31  0.10
2026-12-31  0.14
2027-12-31  0.18
2028-12-31  0.22
2029-12-31  0.26
2030-12-31  0.30
2031-12-31  0.40
2032-12-31  0.50
2033-12-31  0.60
2034-12-31  0.70
2035-12-31  0.80
2036-12-31  0.80
2037-12-31  0.80
2038-12-31  0.80
2039-12-31  0.80
2040-12-31  0.80

In [137]:
  diffusion= {
    "fraction_2025": '0.1',
    "fraction_2030": 0.3,
    "fraction_2035": 0.8
  }

# rename all keys to remove fraction_    
for k in diffusion.keys(): 
    diffusion[re.sub('fraction_', '', k)] = diffusion.pop(k)
    
    
# # The first and last year of the simulation period needs to be defined
# if '2020' not in diffusion.keys():
#     diffusion['2020'] = None
# if '2040' not in diffusion.keys():
#     diffusion['2040'] = None
    
# The diffusion fraction dictionary is converted to a pandas dataframe
df = pd.DataFrame(diffusion.items(), columns=['years','diff'])
df['years'] = df['years'].str.replace('fraction_','')
if '2020' not in df['years']:
    df.loc[len(df.index)] = ['2020', None] 
if '2040' not in df['years']:
    df.loc[len(df.index)] = ['2040', None] 



# The years column is used as index
df['years'] = pd.to_datetime(df['years'])
df.index = df['years']
df.drop(['years'], axis=1, inplace=True)
# Force all values to be floats
df["diff"] = pd.to_numeric(df["diff"], downcast="float")
# The data are resampled yearly
df = df.resample('Y').mean()
# If there is any value greater than 1, set it to 1
if (df3['diff']>1).any():
    print('WARNING: Some declared diffusion fractions are greater than 1. Their value has been changed to 1.')
    df.loc[df['diff']>1, 'diff'] = 1
# if there is any value smaller than 0, set it to 0
if (df3['diff']<0).any():
    print('WARNING: Some declared diffusion fractions are smaller than 0. Their value has been changed to 0.')
    df.loc[df['diff']<0, 'diff'] = 0
# The data are interpolated to fill up values for each year
df2 = df.interpolate(method='linear', limit_direction='both', limit_area='inside')
# if values for the first and for the last years are not specified, 
# the first declared value is used for all the first years
# and the last declared value is used for all the last years.
if df2['diff'].isnull().values.any():
    print('WARNING: Not enough data were provided for first and last years ' 
          'of the considered simulation period.\n'
          'The simulation will continue assuming plausible diffusion fraction values.')
    df3 = df2.interpolate(method='linear').bfill()
df3

ValueError: Unable to parse string "mm" at position 0

In [113]:
if (df3['diff']>2).any():
    print('uuuuu')